import React from 'react'
import { ScrollView, StyleSheet, Text } from 'react-native'
import Reader from '../../components/Reader';
import { styles } from '../../resources/global';

const Information_3 = () => {

    const text = `2.3 Algunos datos e información importante sobre el suicidio

2.3.1 Datos cuantitativos de interés

Según la Organización mundial de la salud, en su reporte del 17 de Junio del 2021, en el mundo, cada año se suicidan 800.000 personas. Se estima que, por cada tentativa de suicidio en la población, por lo general hay un intento no consumado siendo el factor de riesgo inidvidual el más importante. Se estima que el suicidio es la cuarta causa de muerte en jóvenes de entre 15 a 19 años. El 77 % de los suicidios se da en países de ingresis bajos y medios. Si bie existe un vínculo entre el suicidio y los transtornos mentales (depresión y consumo de alcohol) bien documentado en páises con altos ingresos, otros casos se dan en personas que cometen este acto en situaciones de crisis en donde su capacidad para afrontar tensiones en la vida (problemas económicos, rupturas de relaciones, dolores o enfermades crónicas). Por otra parte, se ha evidenciado que vivir en situaciones de conflicto, catrástrofes, actos violentos, abusos, perdida de seres queridos y sensación de aislamiento entre otras puede generar conductas suicidas. 

Las tasas de suicidio son elevadas en grupos vulnerables como: los refugiados, los migrantes, los indígenas, las personas lesbianas, homosexuales, bisexuales, transexuales e intersexuales y reclusas. En las Américas, se estima que aproximadamente 100.000 se quitan la vida anualmente, según los últimos datos disponibles. La mayoría de los suicidios en la Región se producen en personas de entre 25 y 44 años (36%), y en aquellas de entre 45 y 59 años (26%). Asimismo, la Organización Panamericana de la Salud, en su informe del 9 de septiembre del 2021, en el marco del día de la prevención del suicidio, que tiene lugar el 10 de septiembre de cada año, advirtió que la pandemía del COVID-19 ha aumentado los factores de riesgo asociados a las comportamientos suicidas por lo que hace un llamdo a la prevención. Diferentes reportes han demostrado que la perdida de empleo, la dificil situación económica, los traumas o abusos y los transtornos mentales son factores de riesgo asociados al suicidio. 
En Colombia y según el boletín epidemiológico semanal (25 de abril y mayo de 2021) del  Instituto Nacional de Salud (informe sobre intentos suicidas), situaciones como el teletrabajo, desempleo, estudio en casa y falta de  contacto físico con otras personas que y la adaptación a nuevo hábitos de vida se ha convertido en factores de riesgo. Adicionalmente, el temor a contraer el virus y la  pérdida de seres queridos requieren estrategias de afrontamiento  que pueden generar o exacerbar el trastorno mental, lo cual puede  desencadenar autolesiones o actos suicidas. Sin embargo, la cuantificación de estas conductas a través de los servicios de salud tal vez no refleje con fidelidad su ocurrencia, debido al temor de la población al contagio en estos servicios, y la restricción a la movilidad. 
Durante el 2021 con corte a período III, la notificación de casos de intento de suicidio en Colombia presenta un comportamiento similar a la observada en 2018, 2019 y 2020; inicia con tendencia ascendente en la tasa de incidencia por 100.000 habitantes en las primeras semanas del año y desciende a partir de la semana 1º. Proporcionalmente se presentan tasas inferiores en 2021. Este valor por semana epidemiológica osciló entra 0,7 y 1,1 por 100000 habitantes (de 381 a 587 casos con promedio de 508) en 2021, mientras que en 2020 esta tasa osciló entre 1,0 y 1,5 ( 321 a 751 casos con promedio de 587). 
En todas las semanas epidemiológicas de 2021 la tasa de intento de suicidio por edad es siempre superior en el grupo de 15 a 19 años; oscila entre 2,5 (semanas 1, 2) y 4,0 (semana 9) por 100000 habitantes de este grupo de edad, seguido por el grupo de 20 a 24 años, con menores tasas por semana (entre 1,9 y 2,9), pero aún superior al resto de grupos. Este grupo presenta la tasa más alta en la semana 7. El 47,6 % (2 919) del total de los casos (6 132) en 2021 se encuentra entre los 15 y los 24 años, similar a 2020 (47,9 %; 3 600 casos de 7 509). 
En 2021, 696 municipios han notificado casos (62 % de 1 122), es decir 3,5 % menos que en el año anterior (735 municipios). Un total de  47 municipios, que incluye la capital de 21 entidades territoriales, algunos distritos, y 26 municipios más, notificaron el 62,4% de los casos (3 834); 224 municipios (32 %) notificaron sólo un caso. 
Las conclusiones más importantes de este informe son: 
La notificación del intento de suicidio disminuyó con corte al período III de 2021 con respecto al mismo período de 2020, y presentó tasas de incidencia por semana epidemiológica similares a los años 2018 y 2019. 
Se observa aumento en la proporción de la mayoría de los factores de riesgo, y disminución en la mayoría de los factores desencadenantes presentes en los intentos de suicidio. Los mecanismos utilizados en el intento de suicidio conservan el mismo orden. 
Las tasas de incidencia más altas se presentan de los 15 a los 24 años durante todas las semanas epidemiológicas de 2021. 
Las tasas de incidencia más altas de intento de suicidio se encuentran en las entidades territoriales del eje cafetero (Caldas, Quindío, Risaralda), Tolima, Huila, Putumayo, Caquetá Nariño, y Casanare. 
Sobre el suicidio como acto consumado, en Colombia según el Ministerios de salud, en su informe del 10 de septiembre de 2020, señala que; la conducta suicida, que es un conjunto de eventos complejos, que pueden afectar a personas de cualquier edad o condición; cuando se manifiesta como el suicidio consumado, tiene consecuencias devastadoras además para su fa// alignItems: "center",
// justifyContent: "center",milia y comunidad, y sus efectos son duraderos. Adicionalmente, la pandemia por Covid-19 ha generado diversos efectos en la sociedad actual y más allá de las manifestaciones respiratorias que caracterizan a la enfermedad causada por el SARS-CoV-2, se ha constituido en un factor generador de malestar y sufrimiento para muchas personas a nivel mundial y en Colombia, por lo que diversos estudios prevén aumento de carga de enfermedad mental y del riesgo de conducta suicida. 
En el país las cifras del Instituto Nacional de Salud (INS) registran 28.615 casos de intento de suicidio en 2018, esto es 78,4 casos al día. El 63,4% de estos intentos se presentó en mujeres, 80,5% en las cabeceras municipales y 73,5% en personas entre los 10 y los 29 años de edad (INS, 2019). Para el año 2019 el Instituto Nacional de Salud (INS) informó que se presentaron 30.539 casos de intento de suicidio en el país. En lo que va corrido del año 2020 el número de casos de intento de suicidio ha disminuido en comparación con el 2019 (Vigilancia rutinaria histórica 2007-2019 y Boletines Epidemiológicos Semanales de 2020); al igual que los casos de suicidio (Sistema Integrado de Información de la Protección Social-SISPRO). Por su parte, el Instituto Nacional de Medicina Legal y Ciencias Forenses  registró para 2018 el mayor número de muertes por suicidio en la última década, equivalente al 10,4 % de las muertes por causa externa y siendo predominante entre hombres (82,34 %) y personas entre los 20 a 39 años de edad (43,36 %) (Forensis, 2018).

Para el caso concreto de Caldas, según la secretaria de salud de Caldas, informó que en el corrido del 2021 41 caso de suicidio se reportaron y 503 intentos se registraron, y de acuerdo con el Sistema de Vigilancia Epidemiológica, en el año 2020 el departamento Caldas ocupó los primeros lugares en el país con una tasa de 58 intentos de suicidio por cada 100.000 habitantes cifra que indica la necesidad de intervenir en los diferentes niveles de detección y atención de esta problemática; es por ello que la entidad adelanta diferentes programas en los territorios, entre los que se encuentran: “Es una señal, busca ayuda” “RBC – Rehabilitación Basada en Comunidades”, además de estrategias como grupos de apoyo en salud mental y habilidades para la vida.
Asimismo, el observatorio de salud de Caldas, señala que al revisar el número de intentos de suicidio por cada suicidio consumado por cursos de vida se identifican grandes diferencias, se observa como en la adolescencia la relación de intentos por cada suicidio consumado es de 57 intentos por cada suicidio consumado, mientras que en el adulto y el adulto mayor es inferior a 10. Lo anterior implica profundizar en los factores de riesgo y factores desencadenantes para la conducta suicida que puede propiciar la actual estructura poblacional del departamento de Caldas en donde se generan nuevas dinámicas familiares e individuales. 
Dentro de las conclusiones más importantes de este informe está:
El comportamiento del evento de intento de suicidio por semana epidemiológica en el año 2020 presenta una disminución importante a partir de la semana 12, mayoritariamente las semanas en las cuales se decretó cuarentena estricta se presentó una disminución de los casos de intento de suicidio notificados. 
Durante el año 2020, los 6 mayores centros urbanos de Caldas Manizales, Villamaría, La Dorada, Chinchiná, Anserma y Riosucio agrupan el 73,17 % de los casos y las 6 incidencias más altas las presentan los municipios de Risaralda, Neira, Aguadas, Aránzazu, Marulanda y Manizales, en este sentido, el municipio de Manizales presenta vulnerabilidad para el evento tanto por el riesgo como por impacto. 
La nueva realidad que ha traído consigo la pandemia COVID19 ha generado que como sistema de salud se deba buscar alternativas que promueva la salud mental de la población en los entornos familiares, educativos comunitarios y virtuales. 
Teniendo en cuenta lo antes planteado, la OMS reconoce que el suicidio es una prioridad para la salud pública. Es por ello que, en el 2014, publicó el primer informe mundial sobre este tema, titulado titulado “Prevención del suicidio: un imperativo global”, esta informe tenía como propósito aumenta la sensibilidad respecto a la relevancia del suicidio para la salud pública, otorgando la máxima prioridad a su prevención en los programas mundiales de salud pública.

Acciones para brindar ayuda y para estar atentos

    `;
    return (
        <ScrollView style={styles.textContainer}>
            <Reader text={text.split(" ").slice(0, 60).join(" ")} />
            <Text style={styles.text}>
                {text}
            </Text>
        </ScrollView>
    )
}

export default Information_3;