import React from 'react'
import { ScrollView, StyleSheet, Text } from 'react-native'

const Information = () => {

    const text = `
    
    2.1 ¿Qué es el suicidio? 
La Organización Mundial de la Salud define el suicidio como “un fenómeno multideterminado” (OMS, 2018). Los fenómenos multideterminados exigen que todas las ciencias, disciplinas y campos profesionales renuncien a sus pretensiones de brindar explicaciones e intervenciones totalizantes y nos invitan al diálogo interdisciplinario para comprender e intervenir los fenómenos. Decir que un fenómeno es multideterminado es también una orientación fundamental para la acción, en la medida en que nos permite tomar decisiones sobre cuáles son aquellas determinaciones sobre las que podemos incidir y cuáles están por fuera de nuestro campo de influencia. 
Es decir, si admitimos desde el comienzo las limitaciones de nuestros esfuerzos, podemos focalizar y maximizar el impacto de nuestra incidencia en alguna o algunas determinaciones específicas del fenómeno, renunciando, de antemano, a la ilusión de ser infalibles; con lo cual, estamos contribuyendo, desde una perspectiva científica y técnica, la comprensión e intervención del fenómeno, admitiendo, de antemano, que los alcances de nuestros esfuerzos tienen un límite y que, por lo tanto, no podemos tener una certeza plena del resultado de los mismos.
Es precisamente este carácter multideterminado del fenómeno del suicidio el que justifica que se haya creado, en los años setenta del siglo XX, un campo específico para su estudio e intervención que se llama la suicidología y que este se defina, precisamente, como un campo interdisciplinario en el que se dialoga desde la psicología con las demás disciplinas para la construcción de comprensiones e intervenciones pertinentes. La psicología sirve, por así decirlo, de enlace o puente para que se realice la interlocución de todas las demás disciplinas para la construcción de una.

Determinaciones sociológicas
De las múltiples determinaciones que contribuyen a la comprensión y prevención del suicidio, las que se refieren a las dinámicas sociales son aquellas en las que tenemos mayores posibilidades de incidir en la vida cotidiana desde casi cualquier rol social, profesión u oficio.
Una de las obras más importantes para la comprensión e intervención del fenómeno del suicidio la escribió el sociólogo francés Emile Durkeim a finales del Siglo XIX. Después de más de 120 años, podríamos decir que sigue siendo un referente fundamental para comprender el fenómeno y que muchas investigaciones empíricas contemporáneas confirman la validez de sus planteamientos. También podríamos decir, que en el campo de las ciencias sociales no hay todavía una obra que iguale su importancia en este tema. Algunos de los planteamientos que seguirán a continuación tienen su inspiración fundamental en esta obra, sin pretender hacer una síntesis de la misma, ni ceñirse exclusivamente a ella.
Podríamos decir que este es uno de los principios fundamentales que nos deja la obra de Durkeim, que un ser humano puede llegar al suicidio, tanto por la vía del aislamiento y el aflojamiento de sus vínculos con la comunidad como por la vía del exceso de vinculación con la misma. “Cuando el hombre está desligado de la sociedad se mata fácilmente; fácilmente, también, se mata cuando está con demasiada fuerza integrado a ella” (Durkeim, 2001, pág. 183). Este principio es fundamental para comprender los cuatro tipos de suicidas que nos propone el autor:
Suicida egoísta: resulta de una afirmación del yo individual, frente a la sociedad y en perjuicio de esta. Hay individualidades desmesuradas, que rompiendo todo vinculo de solidaridad se desintegran del tipo social a que pertenecen. Esa separación suele producirse, no por falta de aptitud social, sino por oposición a lo social; no por asocialidad, sino por antisocialidad. Así́ como el suicidio egoísta es un caso de desintegración de determinado tipo social, el altruista es un exceso de integración (Durkhiem, 1928, pág.9)
Suicida altruista: Se produce por una superación de la conducta media social : lo mismo que los hechos honrosos y heroicos que faltan por encima de cierta línea media de conducta. Dos formas le señala Durkheim : la del suicidio-deber y la del suicidio facultativo, producido por exceso de valor o por sobra de fe. En ellas el suicida se elimina de la lucha por la vida obedeciendo a un móvil de debilidad, típicamente desintegrativo. (Durkhiem, 1928, pág.9-10-12)
Suicida anómico: al que carece de regla y de principio y halla su origen en bruscos trastornas del cuerpo social, que rompen su equilibrio y producen en él hondas crisis. Por eso es frecuente su presencia en aquellos tipos sociales que carecen de cohesión, como el mundo mercantil e industrial, que no tiene, como el familiar, el político, el religioso, el corporativo, un elemento aglutinante, de 'suficiente fuerza unitiva. También, por desintegración de los grupos, producida por condiciones de ambiente y por profundas crisis morales, ha sido frecuente el suicidio anómico durante la guerra y subsiste después de ella (…) (Durkhiem, 1928, pág. 10)
Teniendo en cuenta lo antes planteado, para Durkheim (1928), se aprecia una relación del suicidio con hechos biológicos y psíquicos, que son latentes con ciertos estados de determinismo social (pág. 13). Por lo tanto, el suicidio, es un fenómeno social y suceso moral, que halla su basa en el egoísmo o en el altruismo. Cabe señalar, que ciertos factores sociales e individuales forman una red compleja en la etiología del suicidio.	
Dos principios para la intervención
De estos planteamientos podemos derivar un principio fundamental para la prevención de la conducta suicida, podríamos formularlo de esta manera: todo lo que está del lado de la exclusión social, está del lado de los factores de riesgo de suicidio y, todo los que está del lado de la inclusión, está del lado de los factores protectores. Con base en este principio podemos diseñar programas de prevención, contextualizados en todos los escenarios sociales mediante un diagnóstico colectivo de los factores de exclusión más importantes que se presentan allí y el diseño de estrategias participativas para transformar las dinámicas de exclusión y favorecer la inclusión de las personas excluidas.
También nos queda una reflexión crítica sobre el riesgo que representan las comunidades que desarrollan dinámicas totalitarias que pretenden uniformar radicalmente a sus integrantes y borrar las particularidades y las ideas o manifestaciones que difieren de la doctrina que rige al conjunto; igualmente, queda la reflexión sobre el riesgo de llevar a los seres humanos a situaciones límite en que se sientan acorralados.

2.2 Mito y creencias sobre el suicidio.

El que se quiere matar no lo dice: criterio equivocado, pues conduce a no prestar atención a las personas que manifiestan sus ideas suicidas o amenazan con suicidarse. El criterio científico indica que de cada 10 personas que se suicidan, nueve de ellas manifestaron, claramente, sus propósitos y la otra dejo entre ver sus intenciones de acabar con su vida.

El que lo dice no lo hace: criterio equivocado, ya que conduce a minimizar las amenazas suicidas, que pueden considerarse erróneamente como chantaje, manipulaciones, alardes, entre otros. El criterio científico nos dice que todo el que se suicida expresó lo que ocurría con palabras, amenazas, gestos o cambios de conducta.

Si de verdad se hubiese querido matar, se hubiera tirado de un puente: criterio equivocado, que refleja la agresividad que genera estos individuos en aquellos que no están capacitados para abordarlos. El criterio científico indica que todo suicida se encuentra en una situación ambivalente, es decir, con deseos de vivir y de morir. El método elegido, no refleja los deseos de morir de quien lo utiliza y, proporcionarle, otro de mayor letalidad es calificado como un delito de auxilio suicida, penalizado por el código penal vigente.

El sujeto que se repone de una crisis suicida no corre peligro alguno de recaer: criterio equivocado, que conduce a disminuir las medidas de observación estricta del sujeto y la evolución sistematiza del riesgo suicida. Según el criterio científico casi la mitad de los que atravesaron por una crisis suicida y consumaron suicidio, lo llevaron a cabo después de los tres primeros intentos tras la crisis emocional, cuando todos creían que el peligro había pasado. Lo que ocurre es que cuando la persona mejora, sus movimientos se hacen más ágiles, están en condiciones de llevar varias vías de hecho, las ideas suicidas aún persisten antes, y debido a la inactividad o incapacidad de movimiento ágiles, no podía hacerlo.

Todo el que se suicida está deprimido: criterio equivocado que relaciona el suicidio como sinónimo de la depresión, lo cual no se ajusta a los estrictos hallazgos. El criterio científico indica que, aunque toda persona deprimida tiene posibilidades de realizar un intento de suicidio o suicidio, no todos lo que lo hacen presentan este trastorno; la persona puede padecer esquizofrenias, alcoholismo, trastornos de carácter entre otros.

Todo el que se suicida es un enfermo mental: criterio equivocado que intenta encasillar el suicidio como una enfermedad mental. Como criterio científico se encuentra que los enfermos mentales se suicidan con mayor frecuencia que la población en general, pero no necesariamente hay que padecer un trastorno mental para hacerlo. No cabe ninguna duda, todo suicida es una persona que sufre.

Al hablar de suicidio con una persona en riesgo, se le puede incitar a que lo realice: criterio equivocado que infunde temor para abordar la temática del suicidio en quienes están en riesgo de cometerlo. Criterio científico: está demostrado que hablar sobre el suicidio con una persona en tal riesgo, en vez de incitar, promover o inducir en su cabeza esa idea, reduce el peligro de cometerlo y puede será la única posibilidad que ofrezca el sujeto para el análisis de sus propósitos autodestructivos.

Al acercarse a una persona en crisis suicida sin la correspondiente preparación para ello, solo mediante el sentido común, es perjudicial y se pierde el tiempo para su abordaje adecuado: criterio equivocado que intenta limitar la participación de voluntarios en la prevención del suicidio. Criterio científico: si el sentido común hace que otros puedan asumir una postura paciente y atenta escucha, con reales deseos de ayudar al sujeto en crisis a encontrar otras soluciones que no sean el suicidio, se habrá iniciado una prevención.

El suicida desea morir: criterio equivocado que pretende justificar la muerte por suicidio de quienes lo comenten, y, por lo tanto, tarde o temprano lo llevará a cabo. Criterio científico: el suicida está en una posición ambivalente, es decir, desea morir si su vida continúa de la misma manera y desea vivir sin se produjeran pequeños cambios en ella; su se diagnóstica oportunamente esa ambivalencia, se pueden inclinar la balanza hacia la opción de vida.

El que intenta el suicidio es un cobarde: criterio equivocado que pretende evitar el suicidio equiparándolo con una cualidad negativa de la personalidad. Criterio científico: los que intentan el suicidio no son cobardes sino personas que sufren.

El que intenta el suicidio es un valiente: criterio equivocado que pretende equiparar el suicidio con una cualidad positiva de la personalidad, lo cual entorpece su prevención pues lo justifica haciéndolo sinónimo de un atributo imitable y que todos desean poseer. Criterio científico: los que intentan el suicidio no son valientes ni cobardes, pues la valentía y la cobardía son atributos de la personalidad que no se cuantifican o miden según la cantidad de veces que alguien se quita la vida o se la respeta.

Los medios de comunicación no pueden contribuir a la prevención del suicidio: criterio equivocado que pretende continuar emitiendo noticias sensacionalistas sólo para vender, sin tener en cuenta las consecuencias del mensaje emitido. Criterio científico, los medios de comunicación pueden convertirse en un valioso aliado en la prevención del suicidio, si enfocan correctamente la noticia sobre el tema y cumplen las sugerencias de los suicidólogos sobre cómo difundirlas.

2.3 Algunos datos e información importante sobre el suicidio

2.3.1 Datos cuantitativos de interés

Según la Organización mundial de la salud, en su reporte del 17 de Junio del 2021, en el mundo, cada año se suicidan 800.000 personas. Se estima que, por cada tentativa de suicidio en la población, por lo general hay un intento no consumado siendo el factor de riesgo inidvidual el más importante. Se estima que el suicidio es la cuarta causa de muerte en jóvenes de entre 15 a 19 años. El 77 % de los suicidios se da en países de ingresis bajos y medios. Si bie existe un vínculo entre el suicidio y los transtornos mentales (depresión y consumo de alcohol) bien documentado en páises con altos ingresos, otros casos se dan en personas que cometen este acto en situaciones de crisis en donde su capacidad para afrontar tensiones en la vida (problemas económicos, rupturas de relaciones, dolores o enfermades crónicas). Por otra parte, se ha evidenciado que vivir en situaciones de conflicto, catrástrofes, actos violentos, abusos, perdida de seres queridos y sensación de aislamiento entre otras puede generar conductas suicidas. 

Las tasas de suicidio son elevadas en grupos vulnerables como: los refugiados, los migrantes, los indígenas, las personas lesbianas, homosexuales, bisexuales, transexuales e intersexuales y reclusas. En las Américas, se estima que aproximadamente 100.000 se quitan la vida anualmente, según los últimos datos disponibles. La mayoría de los suicidios en la Región se producen en personas de entre 25 y 44 años (36%), y en aquellas de entre 45 y 59 años (26%). Asimismo, la Organización Panamericana de la Salud, en su informe del 9 de septiembre del 2021, en el marco del día de la prevención del suicidio, que tiene lugar el 10 de septiembre de cada año, advirtió que la pandemía del COVID-19 ha aumentado los factores de riesgo asociados a las comportamientos suicidas por lo que hace un llamdo a la prevención. Diferentes reportes han demostrado que la perdida de empleo, la dificil situación económica, los traumas o abusos y los transtornos mentales son factores de riesgo asociados al suicidio. 
En Colombia y según el boletín epidemiológico semanal (25 de abril y mayo de 2021) del  Instituto Nacional de Salud (informe sobre intentos suicidas), situaciones como el teletrabajo, desempleo, estudio en casa y falta de  contacto físico con otras personas que y la adaptación a nuevo hábitos de vida se ha convertido en factores de riesgo. Adicionalmente, el temor a contraer el virus y la  pérdida de seres queridos requieren estrategias de afrontamiento  que pueden generar o exacerbar el trastorno mental, lo cual puede  desencadenar autolesiones o actos suicidas. Sin embargo, la cuantificación de estas conductas a través de los servicios de salud tal vez no refleje con fidelidad su ocurrencia, debido al temor de la población al contagio en estos servicios, y la restricción a la movilidad. 
Durante el 2021 con corte a período III, la notificación de casos de intento de suicidio en Colombia presenta un comportamiento similar a la observada en 2018, 2019 y 2020; inicia con tendencia ascendente en la tasa de incidencia por 100.000 habitantes en las primeras semanas del año y desciende a partir de la semana 1º. Proporcionalmente se presentan tasas inferiores en 2021. Este valor por semana epidemiológica osciló entra 0,7 y 1,1 por 100000 habitantes (de 381 a 587 casos con promedio de 508) en 2021, mientras que en 2020 esta tasa osciló entre 1,0 y 1,5 ( 321 a 751 casos con promedio de 587). 
En todas las semanas epidemiológicas de 2021 la tasa de intento de suicidio por edad es siempre superior en el grupo de 15 a 19 años; oscila entre 2,5 (semanas 1, 2) y 4,0 (semana 9) por 100000 habitantes de este grupo de edad, seguido por el grupo de 20 a 24 años, con menores tasas por semana (entre 1,9 y 2,9), pero aún superior al resto de grupos. Este grupo presenta la tasa más alta en la semana 7. El 47,6 % (2 919) del total de los casos (6 132) en 2021 se encuentra entre los 15 y los 24 años, similar a 2020 (47,9 %; 3 600 casos de 7 509). 
En 2021, 696 municipios han notificado casos (62 % de 1 122), es decir 3,5 % menos que en el año anterior (735 municipios). Un total de  47 municipios, que incluye la capital de 21 entidades territoriales, algunos distritos, y 26 municipios más, notificaron el 62,4% de los casos (3 834); 224 municipios (32 %) notificaron sólo un caso. 
Las conclusiones más importantes de este informe son: 
La notificación del intento de suicidio disminuyó con corte al período III de 2021 con respecto al mismo período de 2020, y presentó tasas de incidencia por semana epidemiológica similares a los años 2018 y 2019. 
Se observa aumento en la proporción de la mayoría de los factores de riesgo, y disminución en la mayoría de los factores desencadenantes presentes en los intentos de suicidio. Los mecanismos utilizados en el intento de suicidio conservan el mismo orden. 
Las tasas de incidencia más altas se presentan de los 15 a los 24 años durante todas las semanas epidemiológicas de 2021. 
Las tasas de incidencia más altas de intento de suicidio se encuentran en las entidades territoriales del eje cafetero (Caldas, Quindío, Risaralda), Tolima, Huila, Putumayo, Caquetá Nariño, y Casanare. 
Sobre el suicidio como acto consumado, en Colombia según el Ministerios de salud, en su informe del 10 de septiembre de 2020, señala que; la conducta suicida, que es un conjunto de eventos complejos, que pueden afectar a personas de cualquier edad o condición; cuando se manifiesta como el suicidio consumado, tiene consecuencias devastadoras además para su fa// alignItems: "center",
// justifyContent: "center",milia y comunidad, y sus efectos son duraderos. Adicionalmente, la pandemia por Covid-19 ha generado diversos efectos en la sociedad actual y más allá de las manifestaciones respiratorias que caracterizan a la enfermedad causada por el SARS-CoV-2, se ha constituido en un factor generador de malestar y sufrimiento para muchas personas a nivel mundial y en Colombia, por lo que diversos estudios prevén aumento de carga de enfermedad mental y del riesgo de conducta suicida. 
En el país las cifras del Instituto Nacional de Salud (INS) registran 28.615 casos de intento de suicidio en 2018, esto es 78,4 casos al día. El 63,4% de estos intentos se presentó en mujeres, 80,5% en las cabeceras municipales y 73,5% en personas entre los 10 y los 29 años de edad (INS, 2019). Para el año 2019 el Instituto Nacional de Salud (INS) informó que se presentaron 30.539 casos de intento de suicidio en el país. En lo que va corrido del año 2020 el número de casos de intento de suicidio ha disminuido en comparación con el 2019 (Vigilancia rutinaria histórica 2007-2019 y Boletines Epidemiológicos Semanales de 2020); al igual que los casos de suicidio (Sistema Integrado de Información de la Protección Social-SISPRO). Por su parte, el Instituto Nacional de Medicina Legal y Ciencias Forenses  registró para 2018 el mayor número de muertes por suicidio en la última década, equivalente al 10,4 % de las muertes por causa externa y siendo predominante entre hombres (82,34 %) y personas entre los 20 a 39 años de edad (43,36 %) (Forensis, 2018).

Para el caso concreto de Caldas, según la secretaria de salud de Caldas, informó que en el corrido del 2021 41 caso de suicidio se reportaron y 503 intentos se registraron, y de acuerdo con el Sistema de Vigilancia Epidemiológica, en el año 2020 el departamento Caldas ocupó los primeros lugares en el país con una tasa de 58 intentos de suicidio por cada 100.000 habitantes cifra que indica la necesidad de intervenir en los diferentes niveles de detección y atención de esta problemática; es por ello que la entidad adelanta diferentes programas en los territorios, entre los que se encuentran: “Es una señal, busca ayuda” “RBC – Rehabilitación Basada en Comunidades”, además de estrategias como grupos de apoyo en salud mental y habilidades para la vida.
Asimismo, el observatorio de salud de Caldas, señala que al revisar el número de intentos de suicidio por cada suicidio consumado por cursos de vida se identifican grandes diferencias, se observa como en la adolescencia la relación de intentos por cada suicidio consumado es de 57 intentos por cada suicidio consumado, mientras que en el adulto y el adulto mayor es inferior a 10. Lo anterior implica profundizar en los factores de riesgo y factores desencadenantes para la conducta suicida que puede propiciar la actual estructura poblacional del departamento de Caldas en donde se generan nuevas dinámicas familiares e individuales. 
Dentro de las conclusiones más importantes de este informe está:
El comportamiento del evento de intento de suicidio por semana epidemiológica en el año 2020 presenta una disminución importante a partir de la semana 12, mayoritariamente las semanas en las cuales se decretó cuarentena estricta se presentó una disminución de los casos de intento de suicidio notificados. 
Durante el año 2020, los 6 mayores centros urbanos de Caldas Manizales, Villamaría, La Dorada, Chinchiná, Anserma y Riosucio agrupan el 73,17 % de los casos y las 6 incidencias más altas las presentan los municipios de Risaralda, Neira, Aguadas, Aránzazu, Marulanda y Manizales, en este sentido, el municipio de Manizales presenta vulnerabilidad para el evento tanto por el riesgo como por impacto. 
La nueva realidad que ha traído consigo la pandemia COVID19 ha generado que como sistema de salud se deba buscar alternativas que promueva la salud mental de la población en los entornos familiares, educativos comunitarios y virtuales. 
Teniendo en cuenta lo antes planteado, la OMS reconoce que el suicidio es una prioridad para la salud pública. Es por ello que, en el 2014, publicó el primer informe mundial sobre este tema, titulado titulado “Prevención del suicidio: un imperativo global”, esta informe tenía como propósito aumenta la sensibilidad respecto a la relevancia del suicidio para la salud pública, otorgando la máxima prioridad a su prevención en los programas mundiales de salud pública.

Acciones para brindar ayuda y para estar atentos

    `;
    return (
        <ScrollView style={styles.body}>
            <Text style={styles.text}>
                {text}
            </Text>
        </ScrollView>
    )
}

const styles = StyleSheet.create({

    body: {
        flex: 1,
        padding: 35
    },

    text: {
        fontSize: 25,
        textAlign: "justify"
    }
});


export default Information